name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Build
      run: docker build -t flask-app .
        
    - name: Test
      run: |
        docker run -d -p 5000:5000 --name test-container flask-app
        sleep 10
        curl -f http://localhost:5000 || exit 1
        docker stop test-container
        
    - name: Check size
      run: |
        echo "Image details:"
        docker images flask-app
        docker history flask-app
